name: Api

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GUTENGUESS_DEPLOY_KEY }}

      - uses: actions/checkout@v4

      - name: Checkout submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Copy env
        run: cp packages/server/.env.example packages/server/.env

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm --filter @gutenku/server lint

      - name: Typecheck
        run: pnpm --filter @gutenku/server typecheck

      - name: Test
        run: pnpm --filter @gutenku/server test

      - name: Build
        run: pnpm --filter @gutenku/front build
